# -*- coding: utf-8 -*-
"""colabtest1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wAY713UpKxWnAT_3QB9f5ShW0aPoXoQ
"""

print("Hello world")

print("Hello Sri Lanka")

"""### Introduction to the Python"""

print("error")